### ISSUE TITLE
AutoGen\IntfExternalObj.pas

### ISSUE THREAD

**Issue by limuzi2012** [delphidabbler/codesnip#52] opened 2022-05-15 14:29 UTC
D11.1 [dcc32 Fatal Error] ActiveText.UHTMLRenderer.pas(22): F2063 Could not compile used unit 'ActiveText.UMain.pas'

**Comment by delphidabbler** [comment] 2022-05-16 06:07
Transferred from `delphidabbler/ delphi-tips`  to `delphidabbler/codesnip `.

**Comment by delphidabbler** [comment] 2022-05-16 07:01
To make any progress with this issue I'm going to need more info.

However, one thought occurs because you referenced `AutoGen\IntfExternalObj.pas`. That file has to be generated (along with some resource files) before CodeSnip will compile.

If you've missed that step, please read [`Build.html`](https://htmlpreview.github.io/?https://github.com/delphidabbler/codesnip/blob/master/Build.html) which describes in detail how to compile CodeSnip. (Note that `Build.html` says you need Inno Setup, HHC and Zip, but you can ignore that if you're not going to create a help file or an installer).

If that doesn't work, please provide more information about what you were doing when you got the error, because I can't reproduce this problem on my setup (I did a clean build just yesterday).

**Comment by delphidabbler** [comment] 2022-07-01 14:05
Over a month without response - closing

**Closed by delphidabbler** 2022-07-01 14:05 UTC
Labels: rejected, not an error
